---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/bom version
    register: bom_test_output
  - name: bom version
    debug:
      msg: '{{ bom_test_output.stdout }}'
