---
- name: Testing andrewrothstein.bom
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'bom version'
      ansible.builtin.command: bom version
      changed_when: false
      register: bom_test_output
    - name: Output from 'bom version'
      ansible.builtin.debug:
        msg: '{{ bom_test_output.stdout }}'
